// React UI overlay for the Star of India interactive globe (layout from the
// Claude Design mock). Globe rendering lives in globe.js.
//
// The logbook data is private and never committed to this public repo.
// voyages-data.js is gitignored and generated by build_globe_data.py in the
// star-of-india repo. Where it is absent (the live site), the page asks for
// the file once and keeps it in this browser's localStorage — it is never
// uploaded anywhere.

const { useState, useEffect, useRef, useMemo } = React;
const html = htm.bind(React.createElement);

const STORE_KEY = 'soi.data.v1';
const THEME = new URLSearchParams(location.search).get('theme') || 'parchment';
document.body.setAttribute('data-theme', THEME);
const MONTHS = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];

function parseDataFile(text) {
  const json = text.trim().replace(/^window\.SOI_DATA\s*=\s*/, '').replace(/;\s*$/, '');
  const data = JSON.parse(json);
  if (!Array.isArray(data.voyages) || !data.ports) throw new Error('Not a voyages-data file');
  return data;
}

function storedData() {
  try { const s = localStorage.getItem(STORE_KEY); return s ? JSON.parse(s) : null; }
  catch (e) { return null; }
}

function Root() {
  const [data, setData] = useState(() => window.SOI_DATA || storedData());
  return data ? html`<${App} data=${data} />` : html`<${Loader} onData=${setData} />`;
}

function Loader({ onData }) {
  const [err, setErr] = useState('');
  const onFile = e => {
    const f = e.target.files[0]; if (!f) return;
    f.text().then(t => {
      const d = parseDataFile(t);
      try { localStorage.setItem(STORE_KEY, JSON.stringify(d)); } catch (x) { /* still show it */ }
      onData(d);
    }).catch(x => setErr('That file could not be read: ' + x.message));
  };
  return html`
    <div className="topbar">
      <div className="brand">
        <div className="eyebrow">Maritime Museum · San Diego</div>
        <div className="title">Star of India</div>
        <div className="subtitle">Log Book Vol. 10 · 1897 – 1900</div>
      </div>
    </div>
    <div className="loader">
      <div className="eyebrow">Private logbook data</div>
      <h2>Open the voyage data</h2>
      <p>The transcription isn't published with this page. Choose <b>voyages-data.js</b> —
        it stays in this browser and is never uploaded.</p>
      <label className="pick">Choose file
        <input type="file" accept=".js,.json,text/javascript,application/json" onChange=${onFile} />
      </label>
      ${err && html`<div className="err">${err}</div>`}
    </div>`;
}

function App({ data }) {
  const voyages = data.voyages;
  const ports = data.ports;
  const [voyageIdx, setVoyageIdx] = useState(0);
  const [progress, setProgress] = useState(1);
  const [playing, setPlaying] = useState(false);
  const [hover, setHover] = useState(null);
  const [selected, setSelected] = useState(null);
  const [isIdle, setIsIdle] = useState(false);
  const [ready, setReady] = useState(false);
  const idleTimer = useRef(null);
  const cycleTimer = useRef(null);
  const playRef = useRef({ raf: null, t0: 0 });

  const voyage = voyages[voyageIdx] || voyages[0];

  // --- init globe once ---
  useEffect(() => {
    const cv = document.getElementById('globe-canvas');
    window.Globe.init({ canvas: cv, theme: THEME, ports }).then(() => {
      window.Globe.onHover((hit, x, y) => setHover(hit ? { ...hit, x, y } : null));
      window.Globe.onClick(hit => {
        setSelected(hit);
        if (hit.kind === 'port') window.Globe.pulsePort(hit.key);
      });
      setReady(true);
    });
  }, []);

  // --- voyage change ---
  useEffect(() => {
    if (!ready) return;
    setProgress(1);
    setSelected(null);
    window.Globe.setVoyage(voyage, 1);
    window.Globe.focusVoyage(voyage);
  }, [voyageIdx, ready]);

  // --- progress -> globe ---
  useEffect(() => { if (ready) window.Globe.setVoyage(voyage, progress); }, [progress]);

  // --- playback animation ---
  useEffect(() => {
    if (!playing) {
      if (playRef.current.raf) cancelAnimationFrame(playRef.current.raf);
      return;
    }
    const startProgress = progress >= 1 ? 0 : progress;
    setProgress(startProgress);
    playRef.current.t0 = performance.now();
    const dur = 9000;
    function step() {
      const p = Math.min(1, startProgress + (performance.now() - playRef.current.t0) / dur);
      setProgress(p);
      if (p < 1) playRef.current.raf = requestAnimationFrame(step);
      else setPlaying(false);
    }
    playRef.current.raf = requestAnimationFrame(step);
    return () => { if (playRef.current.raf) cancelAnimationFrame(playRef.current.raf); };
  }, [playing]);

  // --- idle detection ---
  useEffect(() => {
    const reset = () => {
      setIsIdle(false);
      clearTimeout(idleTimer.current);
      idleTimer.current = setTimeout(() => setIsIdle(true), 30000);
    };
    reset();
    const evs = ['pointerdown', 'pointermove', 'keydown', 'wheel'];
    evs.forEach(ev => window.addEventListener(ev, reset, { passive: true }));
    return () => { evs.forEach(ev => window.removeEventListener(ev, reset)); clearTimeout(idleTimer.current); };
  }, []);

  // --- idle auto cycle ---
  useEffect(() => {
    clearInterval(cycleTimer.current);
    if (!ready) return;
    if (isIdle) {
      window.Globe.setIdle(true);
      window.Globe.setRotation(0.0012);
      cycleTimer.current = setInterval(() => {
        setVoyageIdx(v => (v + 1) % voyages.length);
        setPlaying(true);
      }, 14000);
    } else {
      // Active use: stop auto-spin so the selected voyage stays framed.
      window.Globe.setIdle(false);
    }
    return () => clearInterval(cycleTimer.current);
  }, [isIdle, ready]);

  // --- timeline scale (by date, not decade: the volume spans three years) ---
  const tl = useMemo(() => {
    const t0 = Date.parse(data.range[0].slice(0, 7) + '-01');
    const t1 = Date.parse(data.range[1]) + 30 * 86400000;
    const pos = iso => ((Date.parse(iso) - t0) / (t1 - t0)) * 100;
    const years = [];
    for (let y = +data.range[0].slice(0, 4) + 1; y <= +data.range[1].slice(0, 4); y++) years.push(y);
    return { pos, years, first: +data.range[0].slice(0, 4), last: +data.range[1].slice(0, 4) };
  }, [data]);

  const track = voyage.track || [];
  const head = track[Math.min(track.length - 1, Math.round(progress * (track.length - 1)))];
  const headDate = (head && head.date) || voyage.start;

  return html`
    <div className="topbar">
      <div className="brand">
        <div className="eyebrow">Maritime Museum · San Diego</div>
        <div className="title">Star of India</div>
        <div className="subtitle">Log Book Vol. 10 · ${tl.first} – ${tl.last}</div>
      </div>
      <div className="compass"><${Compass} /></div>
    </div>

    <div className="voyage-list">
      <div className="header">
        <div className="lbl">Voyages</div>
        <div className="count">${voyages.length}</div>
      </div>
      <div className="scroll">
        ${voyages.map((v, i) => html`
          <div key=${v.id} className=${'voyage-row' + (i === voyageIdx ? ' active' : '')}
               onClick=${() => setVoyageIdx(i)}>
            <div className="num">№ ${String(i + 1).padStart(2, '0')}</div>
            <div className="name">${v.name}</div>
            <div className="yr">${v.year}</div>
          </div>`)}
      </div>
    </div>

    <div className="legend">
      <div className="row"><span className="swatch"></span>Route</div>
      <div className="row"><span className="swatch dot"></span>Port of call</div>
      <div className="row"><span className="swatch dot small"></span>Noon position</div>
      <div className="row"><span className="swatch dot small dim"></span>By account (no sight)</div>
      <div className="row" style=${{ marginTop: 4, color: 'var(--ink-dim)' }}>
        Drag to spin · Scroll to zoom · Tap a dot
      </div>
    </div>

    <${DetailPanel} voyage=${voyage} voyageIdx=${voyageIdx} ports=${ports}
                    selected=${selected} onClose=${() => setSelected(null)} />

    ${hover && html`
      <div className="port-label show" style=${{ left: hover.x, top: hover.y }}>
        ${hover.kind === 'port'
          ? html`<div className="pl-name">${ports[hover.key].name}</div>
                 <div className="pl-region">${ports[hover.key].region}</div>`
          : html`<div className="pl-name">${fmtDate(hover.day.date)}${hover.day.repeat ? ' (2nd)' : ''}</div>
                 <div className="pl-region">${hover.day.label || hover.day.weather || fmtPos(hover.day)}</div>`}
      </div>`}

    <div className="timeline">
      <div className="tl-head">
        <span>Timeline · ${tl.first} – ${tl.last}</span>
        <span className="yr">${voyage.year}</span>
      </div>
      <div className="tl-track">
        <div className="axis"></div>
        ${tl.years.map(y => html`
          <${React.Fragment} key=${y}>
            <div className="tick major" style=${{ left: tl.pos(y + '-01-01') + '%' }}></div>
            <div className="tick-lbl" style=${{ left: tl.pos(y + '-01-01') + '%' }}>${y}</div>
          <//>`)}
        ${voyages.map((v, i) => html`
          <div key=${v.id} className=${'vmark' + (i === voyageIdx ? ' active' : '')}
               style=${{ left: tl.pos(v.start) + '%' }}
               title=${`${fmtDate(v.start)} — ${v.name}`}
               onClick=${() => setVoyageIdx(i)}></div>`)}
        <div className="scrubber" style=${{ left: tl.pos(headDate) + '%' }}></div>
      </div>
      <div className="tl-controls">
        <button onClick=${() => setPlaying(p => !p)}>${playing ? '◼ Pause' : '▶ Play voyage'}</button>
        <span>Sail progress</span>
        <div className="progress"><div style=${{ width: (progress * 100) + '%' }}></div></div>
        <span>${fmtDate(headDate)}</span>
        <button onClick=${() => setVoyageIdx(v => Math.max(0, v - 1))}>‹ Prev</button>
        <button onClick=${() => setVoyageIdx(v => Math.min(voyages.length - 1, v + 1))}>Next ›</button>
      </div>
    </div>

    <div className=${'attract' + (isIdle ? ' on' : '')}>Touch to explore — ${voyages.length} voyages</div>`;
}

function DetailPanel({ voyage, voyageIdx, ports, selected, onClose }) {
  const calls = (voyage.ports || []).map(k => ({ key: k, ...ports[k] })).filter(p => p.name);
  const port = selected && selected.kind === 'port' ? ports[selected.key] : null;
  const day = selected && selected.kind === 'day' ? selected.day : null;
  const k = { fontFamily: 'var(--mono)', fontSize: 11, color: 'var(--ink-dim)', letterSpacing: '.14em', marginTop: 2 };
  const clear = html`<button onClick=${onClose} style=${{
    background: 'transparent', border: '1px solid var(--panel-edge)',
    color: 'var(--ink-mute)', fontFamily: 'var(--mono)', fontSize: 10,
    letterSpacing: '.18em', padding: '4px 8px', cursor: 'pointer'
  }}>CLEAR</button>`;
  return html`
    <div className="detail">
      <div className="head">
        <div className="eyebrow">№ ${String(voyageIdx + 1).padStart(2, '0')} · ${voyage.year}</div>
        <h2>${voyage.name}</h2>
        <div className="dates">
          ${fmtDate(voyage.start)} — ${fmtDate(voyage.end)} · ${durationDays(voyage)} days
        </div>
      </div>
      <div className="body">
        ${port && html`
          <div className="selected">
            <div className="stat">
              <div className="k">Selected port</div>
              <div className="v small row-between"><span>${port.name}</span>${clear}</div>
              <div style=${k}>${port.region} · ${fmtCoord(port.lat, 'lat')} ${fmtCoord(port.lon, 'lon')}</div>
            </div>
          </div>`}
        ${day && html`
          <div className="selected">
            <div className="stat">
              <div className="k">${day.port ? 'Port' : day.approx ? 'Approximate position' : day.dr ? 'Noon · by account' : 'Noon position'}</div>
              <div className="v small row-between">
                <span>${fmtDate(day.date)}${day.repeat ? ' (repeated date)' : ''}</span>${clear}
              </div>
              <div style=${k}>${fmtPos(day)}${day.page ? ` · PDF p. ${day.page}` : ''}</div>
            </div>
            ${(day.course || day.dist || day.wind || day.baro) && html`
              <div className="stat-grid day-grid">
                ${day.course && html`<div className="stat"><div className="k">Course</div><div className="v small">${day.course}</div></div>`}
                ${day.dist != null && html`<div className="stat"><div className="k">Run</div><div className="v small">${day.dist} nm</div></div>`}
                ${day.wind && html`<div className="stat"><div className="k">Wind</div><div className="v small">${day.wind}</div></div>`}
                ${(day.baro || day.therm) && html`<div className="stat"><div className="k">Bar · Temp</div><div className="v small">${day.baro || '—'} · ${day.therm ? day.therm + '°' : '—'}</div></div>`}
              </div>`}
            ${day.weather && html`<div className="day-weather">${day.weather}</div>`}
            ${day.log && html`<div className="note">"${day.log}"</div>`}
          </div>`}

        <div className="stat-grid">
          <div className="stat"><div className="k">Master</div><div className="v small">${voyage.master}</div></div>
          <div className="stat"><div className="k">Mate</div><div className="v small">${voyage.mate}</div></div>
          <div className="stat"><div className="k">Log days</div><div className="v">${voyage.logDays}</div></div>
          <div className="stat"><div className="k">Noon fixes</div><div className="v">${voyage.fixDays}<span style=${{ fontSize: 12, color: 'var(--ink-mute)' }}> · ${voyage.drDays} DR</span></div></div>
          <div className="stat"><div className="k">Distance run</div><div className="v">${voyage.distance ? voyage.distance.toLocaleString() : '—'}<span style=${{ fontSize: 12, color: 'var(--ink-mute)' }}>${voyage.distance ? ' nm' : ''}</span></div></div>
          <div className="stat"><div className="k">Calls</div><div className="v">${calls.length}</div></div>
        </div>
        ${voyage.complete === false && html`
          <div style=${{
            fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '.2em',
            textTransform: 'uppercase', color: 'var(--accent)',
            border: '1px dashed var(--accent)', padding: '6px 8px',
            marginBottom: 12, textAlign: 'center'
          }}>Incomplete in this volume</div>`}

        <div className="k" style=${{
          fontFamily: 'var(--mono)', fontSize: 10, letterSpacing: '.22em',
          textTransform: 'uppercase', color: 'var(--ink-mute)', marginBottom: 6
        }}>Ports of call</div>
        <ul className="ports-list">
          ${calls.map((p, i) => html`
            <li key=${i}><span className="dot"></span><span className="nm">${p.name}</span><span className="rg">${p.region}</span></li>`)}
        </ul>

        <div className="note">"${voyage.notes}"</div>
        <div style=${{
          marginTop: 14, fontFamily: 'var(--mono)', fontSize: 10,
          letterSpacing: '.2em', color: 'var(--ink-dim)', textTransform: 'uppercase'
        }}>Log Book Vol. 10 · PDF pp. ${voyage.pages.filter(Boolean).join('–')}</div>
      </div>
    </div>`;
}

function Compass() {
  return html`
    <svg viewBox="0 0 100 100" fill="none">
      <circle cx="50" cy="50" r="46" stroke="currentColor" strokeWidth="0.6" opacity="0.5"/>
      <circle cx="50" cy="50" r="36" stroke="currentColor" strokeWidth="0.4" opacity="0.3"/>
      <g stroke="currentColor" strokeWidth="0.5" opacity="0.6">
        ${Array.from({ length: 16 }).map((_, i) => {
          const a = (i / 16) * Math.PI * 2;
          const r1 = i % 4 === 0 ? 30 : 38, r2 = 44;
          return html`<line key=${i} x1=${50 + Math.cos(a) * r1} y1=${50 + Math.sin(a) * r1}
                            x2=${50 + Math.cos(a) * r2} y2=${50 + Math.sin(a) * r2} />`;
        })}
      </g>
      <polygon points="50,12 54,50 50,50" fill="var(--route)"/>
      <polygon points="50,88 46,50 50,50" fill="currentColor" opacity="0.5"/>
      <text x="50" y="9" textAnchor="middle" fontSize="8"
            fontFamily="var(--mono)" fill="currentColor" letterSpacing="2">N</text>
    </svg>`;
}

function fmtDate(iso) {
  if (!iso) return '—';
  const [y, m, d] = iso.split('-');
  return `${parseInt(d, 10)} ${MONTHS[parseInt(m, 10) - 1]} ${y}`;
}
function durationDays(v) {
  if (!v.start || !v.end) return '—';
  return Math.round((new Date(v.end) - new Date(v.start)) / 86400000);
}
function fmtCoord(val, kind) {
  const dir = kind === 'lat' ? (val >= 0 ? 'N' : 'S') : (val >= 0 ? 'E' : 'W');
  return `${Math.abs(val).toFixed(2)}°${dir}`;
}
function fmtPos(d) {
  return d.latText ? `${d.latText} ${d.lonText}` : `${fmtCoord(d.lat, 'lat')} ${fmtCoord(d.lon, 'lon')}`;
}

ReactDOM.createRoot(document.getElementById('root')).render(html`<${Root} />`);
